url:
  saveModelUrl: http://localhost:8080/mdvn-model-sapi/models/saveModel
  rtrvModelListUrl: http://localhost:8080/mdvn-model-sapi/models
  rtrvModelListByTypeUrl: http://localhost:8080/mdvn-model-sapi/modelsByType
  updateQuoteCntUrl: http://localhost:8080/mdvn-model-sapi/models
  findByNameUrl : http://localhost:8080/mdvn-model-sapi/models/model
  findByIdUrl: http://localhost:8080/mdvn-model-sapi/models/findById
  findModelDetailByIdUrl: http://localhost:8080/mdvn-model-sapi/models/findModelDetailById


