url:
  saveTagUrl: http://localhost:10002/mdvn-tag-s/tags/tag
  rtrvTagListUrl: http://localhost:10002/mdvn-tag-s/tags
  updateQuoteCntUrl: http://localhost:10002/mdvn-tag-s/tags
  rtrvTagsUrl: http://localhost:10002/mdvn-tag-s/tagList
  findByNameUrl : http://localhost:10002/mdvn-tag-s/tags/tag
  findByIdUrl : http://localhost:10002/mdvn-tag-s/tags/{tagId}/tag


