url:
  saveTagUrl: http://localhost:10002/mdvn-tag-s/tags/tag
  rtrvTagListUrl: http://localhost:10002/mdvn-tag-s/tags
  updateQuoteCntUrl: http://localhost:10002/mdvn-tag-s/tags
  findByNameUrl : http://localhost:10002/mdvn-tag-s/tags/tag