url:
  saveTagUrl: http://localhost:10002/mdvn-tag-s/tags/tag
  rtrvTagListUrl: http://localhost:10002/mdvn-tag-s/tags
  updateQuoteCntUrl: http://localhost:10002/mdvn-tag-s/tags
<<<<<<< HEAD
  findByNameUrl : http://localhost:10002/mdvn-tag-s/tags/tag
=======
  getTagIdByUuIdUrl: http://localhost:10002/mdvn-tag-s/getTagIdByUuId
>>>>>>> 29a5f170fe0b2f4b8c1402144187839255cad32b
