config:
  rtrvProjInfoListUrl: http://localhost:8080/mdvn-project-sapi/project/rtrvProjInfoList
  createProjectUrl: http://localhost:8080/mdvn-project-sapi/project/createProject
  saveProjectBaseUrl: http://localhost:8080/mdvn-project-sapi/project/saveProject
  savePTagsUrl: http://localhost:8080/mdvn-project-sapi/project/savePTags
  savePModelsUrl: http://localhost:8080/mdvn-project-sapi/project/savePModels
  saveCheckListsUrl: http://localhost:8080/mdvn-project-sapi/project/savePCheckLists
  checklistsListByUuIdUrl: http://localhost:8080/mdvn-project-sapi/project/checklistsListByUuId
  savePAttchUrlsUrl: http://localhost:8080/mdvn-project-sapi/project/savePAttchUrls
  savePLeadersUrl: http://localhost:8080/mdvn-project-sapi/project/savePLeaders
  updateProjBaseInfoUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjBaseInfo
  updateProjLeadersUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjLeaders
  updateProjAttchUrlsUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjAttchUrls
  updateProjTagsUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjTags
  updateProjChecklistsUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjChecklists
  updateProjModelsUrl: http://localhost:8080/mdvn-project-sapi/updateProject/updateProjModels
  rtrvProjBaseInfoUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjBaseInfo
  rtrvProjLedersUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjLeders
  rtrvProjTagsUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjTags
  rtrvProjModelsUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjModels
  rtrvProjCheckListsUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjCheckLists
  rtrvProjAttUrlsUrl: http://localhost:8080/mdvn-project-sapi/projDetail/rtrvProjAttUrls
  rtrvReqmntListUrl: http://localhost:8080/mdvn-reqmnt-sapi/rtrvReqmntList
  rtrvAttchListUrl: http://localhost:8080/mdvn-file-sapi/files/
  rtrvCommentInfosUrl: http://localhost:8080/mdvn-comment-sapi/comments/rtrvCommentInfos
  rtrvStaffInfoUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffInfo
  rtrvStaffsByIdsUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffListByStaffIdList
  rtrvReqmntMembersUrl: http://localhost:8080/mdvn-reqmnt-sapi/rtrvReqmntMembers
  #  websocket推送信息测试
  sendMessageUrl: http://localhost:8080/mdvn-websocket/websocket/sendMessage

