url:
  rtrvStaffListUrl: http://localhost:8080/mdvn-staff-sapi/staffList
  rtrvStaffListByStaffIdListUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffListByStaffIdList
  rtrvStaffInfoUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffInfo
  rtrvStaffListByNameUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffListByName

  assignAuthUrl : http://localhost:8080/mdvn-staff-sapi/staffAuth
  rtrvAuthUrl : http://localhost:8080/mdvn-staff-sapi/rtrvAuth
  findByIdUrl : http://localhost:8080/mdvn-staff-sapi/staff

  createStaffUrl: http://localhost:8080/mdvn-staff-sapi/createStaff
  rtrvStaffDetailUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffDetail
  rtrvStaffTagListUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffTagList
  updateStaffDetailUrl: http://localhost:8080/mdvn-staff-sapi/updateStaffDetail
  rtrvTagsUrl: http://localhost:8080/mdvn-tag-sapi/tags/rtrvTags

  rtrvPostionDetailUrl: http://localhost:8080/mdvn-department-sapi/findPositionById
  rtrvDepartmentDetailUrl: http://localhost:8080/mdvn-department-sapi/findDepartmentById
  findByAccounAndPasswordtUrl : http://localhost:8080/mdvn-staff-sapi/staff