url:
  rtrvStaffListUrl: http://localhost:10013/mdvn-staff-sapi/staffList
  rtrvStaffListByStaffIdListUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffListByStaffIdList
  rtrvStaffInfoUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffInfo
  rtrvStaffListByNameUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffListByName

  assignAuthUrl : http://localhost:10013/mdvn-staff-sapi/staffAuth
  rtrvAuthUrl : http://localhost:10013/mdvn-staff-sapi/rtrvAuth
  findByIdUrl : http://localhost:10013/mdvn-staff-sapi/staff

  createStaffUrl: http://localhost:10013/mdvn-staff-sapi/createStaff
  rtrvStaffDetailUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffDetail
  rtrvTagsUrl: http://localhost:10002/mdvn-tag-sapi/tags/rtrvTags
  rtrvStaffTagListUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffTagList
  updateStaffDetailUrl: http://localhost:10013/mdvn-staff-sapi/updateStaffDetail
  deleteStaffUrl: http://localhost:10013/mdvn-staff-sapi/deleteStaff

  rtrvPostionDetailUrl: http://localhost:10023/mdvn-department-sapi/findPositionById
  rtrvDepartmentDetailUrl: http://localhost:10023/mdvn-department-sapi/findDepartmentById




