server:
  port: 8080
  context-path: /mdvn-task-sapi
spring:
  datasource:
    url: jdbc:mysql://192.168.0.254/db_mdvn_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: tom
    password: tom