server:
  port: 80
  context-path: /mdvn-task-sapi
spring:
  datasource:
    url: jdbc:mysql://47.100.100.211/db_mdvn?useUnicode=true&characterEncoding=utf8&useSSL=false

    username: mdvn
    password: mdvn