url:
  createCommentInfoUrl: http://localhost:8080/mdvn-comment-sapi/comments/createCommentInfo
  rtrvStaffInfoUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffInfo
  likeOrDislikeUrl: http://localhost:8080/mdvn-comment-sapi/comments/likeOrDislike





