config:
  judgeSubLabelIdUrl: http://localhost:8080/mdvn-model-sapi/models/judgeSubLabelId
  createStoryUrl: http://localhost:8080/mdvn-story-sapi/story/createStory
  saveStoryBaseUrl: http://localhost:8080/mdvn-story-sapi/story/saveStory
  savePTagsUrl: http://localhost:8080/mdvn-story-sapi/story/savePTags
  savePModelsUrl: http://localhost:8080/mdvn-story-sapi/story/savePModels
  saveCheckListsUrl: http://localhost:8080/mdvn-story-sapi/story/savePCheckLists
  checklistsListByUuIdUrl: http://localhost:8080/mdvn-story-sapi/story/checklistsListByUuId
  savePAttchUrlsUrl: http://localhost:8080/mdvn-story-sapi/story/savePAttchUrls
  savePLeadersUrl: http://localhost:8080/mdvn-story-sapi/story/savePLeaders
  updateStoryBaseInfoUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryBaseInfo
  updateStoryMembersUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryMembers
  updateStoryAttchUrlsUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryAttchUrls
  updateStoryTagsUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryTags
  updateStoryChecklistsUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryChecklists
  updateStoryModelsUrl: http://localhost:8080/mdvn-story-sapi/updateStory/updateStoryModels
  rtrvStoryBaseInfoUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvStoryBaseInfo
  rtrvSRoleMembersUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvSRoleMembers
  rtrvStoryTagsUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvStoryTags
  rtrvStoryModelsUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvStoryModels
  rtrvStoryCheckListsUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvStoryCheckLists
  rtrvStoryAttUrlsUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvStoryAttUrls
  rtrvReqmntListUrl: http://localhost:8080/mdvn-reqmnt-papi/rtrvReqmntList

  rtrvMembersByRoleIdUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/rtrvMembersByRoleId
  labelIdByStoryIdUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/getLabelIdByStoryId
  modelIdByStoryIdUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/getModelIdByStoryId
  rtrvReqmntMembersUrl : http://localhost:8080/mdvn-reqmnt-sapi/rtrvReqmntMembers
  reqmntIdByStoryIdUrl: http://localhost:8080/mdvn-story-sapi/storyDetail/getReqmntIdByStoryId
# staff sapi urls
  rtrvStaffsByIdsUrl: http://localhost:8080/mdvn-staff-sapi/rtrvStaffListByStaffIdList


# tag sapi urls
  rtrvTagsByIdsUrl: http://localhost:8080/mdvn-tag-sapi/tags/rtrvTags

# model sapi urls
  rtrvFuncLabelUrl: http://localhost:8080/mdvn-model-sapi/models/findFuncById
  rtrvModelRoleByModelIdUrl: http://localhost:8080/mdvn-model-sapi/models/findById
  rtrvRoleByRoleIdUrl: http://localhost:8080/mdvn-model-sapi/models/findRoleById

  rtrvStoryInfoListUrl: http://localhost:8080/mdvn-story-sapi/story/rtrvStoryInfoList
  rtrvTaskListByStoryIdUrl: http://localhost:8080/mdvn-task-papi/task/retrieveTaskList
