config:
#  rtrvProjInfoListUrl: http://localhost:10005/mdvn-project-sapi/project/rtrvProjInfoList
#  createProjectUrl: http://localhost:10005/mdvn-project-sapi/project/createProject
#  saveProjectBaseUrl: http://localhost:10005/mdvn-project-sapi/project/saveProject
#  getProjIdByUuIdUrl: http://localhost:10005/mdvn-project-sapi/project/getProjIdByUuId
#  savePTagsUrl: http://localhost:10005/mdvn-project-sapi/project/savePTags
#  savePModelsUrl: http://localhost:10005/mdvn-project-sapi/project/savePModels
#  saveCheckListsUrl: http://localhost:10005/mdvn-project-sapi/project/savePCheckLists
#  getChecklistsListByUuIdUrl: http://localhost:10005/mdvn-project-sapi/project/getChecklistsListByUuId
#  savePAttchUrlsUrl: http://localhost:10005/mdvn-project-sapi/project/savePAttchUrls
#  savePLeadersUrl: http://localhost:10005/mdvn-project-sapi/project/savePLeaders

  saveReqmntUrl: http://localhost:10012/mdvn-reqmnt-sapi/saveReqmnt
  saveRMembersUrl: http://localhost:10012/mdvn-reqmnt-sapi/saveRMembers
  saveRTagsUrl: http://localhost:10012/mdvn-reqmnt-sapi/saveRTags
  saveRCheckListUrl: http://localhost:10012/mdvn-reqmnt-sapi/saveRCheckLists
  saveRAttchUrl: http://localhost:10012/mdvn-reqmnt-sapi/saveRAttchUrls

  rtrvReqmntInfoUrl: http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntInfo
  rtrvReqmntListUrl: http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntList
  rtrvReqmntTagsUrl: http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntTags
  rtrvReqmntMembersUrl : http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntMembers
  rtrvReqmntCheckListUrl : http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntCheckList
  rtrvReqmntAttchsUrl: http://localhost:10012/mdvn-reqmnt-sapi/rtrvReqmntAttUrls
  updateReqmntInfoUrl: http://localhost:10012/mdvn-reqmnt-sapi/updateReqmntInfo


# staff sapi urls
  rtrvStaffsByIdsUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffListByStaffIdList

# tag sapi urls
  rtrvTagsByIdsUrl: http://localhost:10002/mdvn-tag-sapi/tags/rtrvTags

# model sapi urls
  rtrvFuncLabelUrl: http://localhost:10009/mdvn-model-sapi/models/findFuncById
  findSubFuncListByIdUrl: http://localhost:10009/mdvn-model-sapi/models/findSubFuncListById
  rtrvModelRoleByModelIdUrl: http://localhost:10009/mdvn-model-sapi/models/findById
  judgeLabelIdUrl: http://localhost:10009/mdvn-model-sapi/models/judgeLabelId
  rtrvStoryInfoListUrl: http://localhost:10015/mdvn-story-sapi/story/rtrvStoryInfoList

# attchment sapi url
  rtrvAttchInfoListUrl: http://localhost:10019/mdvn-file-sapi/files/

  rtrvSRoleMembersUrl: http://localhost:10015/mdvn-story-sapi/storyDetail/rtrvSRoleMembers

  rtrvCommentInfosUrl: http://localhost:10025/mdvn-comment-sapi/comments/rtrvCommentInfos
  rtrvStaffInfoUrl: http://localhost:10013/mdvn-staff-sapi/rtrvStaffInfo
  #  websocket推送信息测试
  sendMessageUrl: http://localhost:10027/mdvn-websocket/websocket/sendMessage


