server:
  port: 80
  context-path: /mdvn-department-sapi
spring:
  datasource:
#    url: jdbc:mysql://47.100.100.211/db_mdvn?useUnicode=true&characterEncoding=utf8&useSSL=false
#
#    username: mdvn
#    password: mdvn

    username: owen
    password: dm@2018
    url: jdbc:mysql://112.74.45.247/db_mdvn?useUnicode=true&characterEncoding=utf8&useSSL=false