server:
  port: 80
  context-path: /mdvn-department-sapi
spring:
  datasource:
    url: jdbc:mysql://192.168.0.254/db_mdvn_prod?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: tom
    password: tom