config:
#  rtrvProjInfoListUrl: http://localhost:10005/mdvn-project-sapi/project/rtrvProjInfoList
#  createProjectUrl: http://localhost:10005/mdvn-project-sapi/project/createProject
#  saveProjectBaseUrl: http://localhost:10005/mdvn-project-sapi/project/saveProject
#  getProjIdByUuIdUrl: http://localhost:10005/mdvn-project-sapi/project/getProjIdByUuId
#  savePTagsUrl: http://localhost:10005/mdvn-project-sapi/project/savePTags
#  savePModelsUrl: http://localhost:10005/mdvn-project-sapi/project/savePModels
#  saveCheckListsUrl: http://localhost:10005/mdvn-project-sapi/project/savePCheckLists
#  getChecklistsListByUuIdUrl: http://localhost:10005/mdvn-project-sapi/project/getChecklistsListByUuId
#  savePAttchUrlsUrl: http://localhost:10005/mdvn-project-sapi/project/savePAttchUrls
#  savePLeadersUrl: http://localhost:10005/mdvn-project-sapi/project/savePLeaders

  saveReqmntUrl: http://localhost/mdvn-reqmnt-sapi/saveReqmnt
  saveRMembersUrl: http://localhost/mdvn-reqmnt-sapi/saveRMembers
  saveRTagsUrl: http://localhost/mdvn-reqmnt-sapi/saveRTags
  saveRCheckListUrl: http://localhost/mdvn-reqmnt-sapi/saveRCheckLists
  saveRAttchUrl: http://localhost/mdvn-reqmnt-sapi/saveRAttchUrls

  rtrvReqmntInfoUrl: http://localhost/mdvn-reqmnt-sapi/rtrvReqmntInfo
  rtrvReqmntListUrl: http://localhost/mdvn-reqmnt-sapi/rtrvReqmntList
  rtrvReqmntTagsUrl: http://localhost/mdvn-reqmnt-sapi/rtrvReqmntTags
  rtrvReqmntMembersUrl : http://localhost/mdvn-reqmnt-sapi/rtrvReqmntMembers
  rtrvReqmntCheckListUrl : http://localhost/mdvn-reqmnt-sapi/rtrvReqmntCheckList
  rtrvReqmntAttchsUrl: http://localhost/mdvn-reqmnt-sapi/rtrvReqmntAttUrls
  updateReqmntInfoUrl: http://localhost/mdvn-reqmnt-sapi/updateReqmntInfo

# staff sapi urls
  rtrvStaffsByIdsUrl: http://localhost/mdvn-staff-sapi/rtrvStaffListByStaffIdList
  rtrvStaffInfoUrl: http://localhost/mdvn-staff-sapi/rtrvStaffInfo

# tag sapi urls
  rtrvTagsByIdsUrl: http://localhost/mdvn-tag-s/tags/rtrvTags

# model sapi urls
  rtrvFuncLabelUrl: http://localhost/mdvn-model-s/models/findFuncById
  rtrvModelRoleByModelIdUrl: http://localhost/mdvn-model-s/models/findById

# task sapi urls
  saveTaskUrl: http://localhost/mdvn-task-sapi/saveTask
  rtrvTaskListUrl: http://localhost/mdvn-task-sapi/rtrvTaskList
  rtrvTaskInfoUrl: http://localhost:10004/mdvn-task-sapi/rtrvTaskInfo
  updateTaskUrl: http://localhost/mdvn-task-sapi/updateTask
  addAttachForTaskUrl: http://localhost/mdvn-task-sapi/addAttachForTask
  deleteAttachForTaskUrl: http://localhost:10004/mdvn-task-sapi/deleteAttachForTask

# attachment sapi urls
  getAttachmentListByIdsUrl: http://localhost/mdvn-file-sapi/files/